# Generated by Django 5.1 on 2024-09-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('노드_유형_코드', models.IntegerField()),
                ('경도', models.FloatField()),
                ('위도', models.FloatField()),
            ],
        ),
    ]
