# Generated by Django 5.1 on 2024-09-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_elevatorlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elevatorlocation',
            options={'managed': False},
        ),
    ]
