# Generated by Django 5.1 on 2024-09-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_elevatorlocation_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='elevatorlocation',
            table='elevator_location',
        ),
    ]
