# Generated by Django 5.1 on 2024-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_elevatorlocation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalatorLocation',
            fields=[
                ('EscID', models.IntegerField(primary_key=True, serialize=False)),
                ('EscKind', models.IntegerField()),
                ('esc_latitude', models.FloatField()),
                ('esc_longitude', models.FloatField()),
            ],
            options={
                'db_table': 'escalator_location',
                'managed': False,
            },
        ),
    ]
